name: First GitHub Actions 

on: [push]

jobs:
  build: 
    runs-on: self-hosted 

    strategy:
      matrix:
        python-version: [3.8, 3.9] 

    steps:
      # Step 1: Check out the repository code into the runner.
      - uses: actions/checkout@v2

      # Step 2: Set up the specified Python version from the matrix.
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install all the dependencies required for the tests.
      - name: Installing all the dependencies
        run: |
          python -m pip install --upgrade pip # Upgrade pip.
          pip install pytest

      # Step 4: Run the tests using pytest.
      - name: Running tests
        run: |
          python -m pytest add.py



